// go.proto
// [python quickstart](https://grpc.io/docs/quickstart/python.html#run-a-grpc-application)

// python -m grpc_tools.protoc --python_out=../python/grpc --grpc_python_out=../python/grpc -I. go.proto
// protoc --proto_path=./pb/ --go_out=plugins=grpc:./grpc go.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: go.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoSayHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GoSayHelloRequest) Reset() {
	*x = GoSayHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoSayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoSayHelloRequest) ProtoMessage() {}

func (x *GoSayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoSayHelloRequest.ProtoReflect.Descriptor instead.
func (*GoSayHelloRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{0}
}

func (x *GoSayHelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GoSayHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GoSayHelloResponse) Reset() {
	*x = GoSayHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoSayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoSayHelloResponse) ProtoMessage() {}

func (x *GoSayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoSayHelloResponse.ProtoReflect.Descriptor instead.
func (*GoSayHelloResponse) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{1}
}

func (x *GoSayHelloResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type NotifyActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   *Base   `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Action *Action `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`
	State  *State  `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *NotifyActionRequest) Reset() {
	*x = NotifyActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyActionRequest) ProtoMessage() {}

func (x *NotifyActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyActionRequest.ProtoReflect.Descriptor instead.
func (*NotifyActionRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyActionRequest) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *NotifyActionRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *NotifyActionRequest) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

type NotifyActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base     *Base     `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Feedback *Feedback `protobuf:"bytes,2,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
}

func (x *NotifyActionResponse) Reset() {
	*x = NotifyActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyActionResponse) ProtoMessage() {}

func (x *NotifyActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyActionResponse.ProtoReflect.Descriptor instead.
func (*NotifyActionResponse) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyActionResponse) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *NotifyActionResponse) GetFeedback() *Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

var File_go_proto protoreflect.FileDescriptor

var file_go_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11,
	0x47, 0x6f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x26, 0x0a, 0x12, 0x47, 0x6f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x78, 0x0a, 0x13, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x46,
	0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x32, 0x8f, 0x01, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x41, 0x70, 0x69, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x6f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f,
	0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_proto_rawDescOnce sync.Once
	file_go_proto_rawDescData = file_go_proto_rawDesc
)

func file_go_proto_rawDescGZIP() []byte {
	file_go_proto_rawDescOnce.Do(func() {
		file_go_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_proto_rawDescData)
	})
	return file_go_proto_rawDescData
}

var file_go_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_go_proto_goTypes = []interface{}{
	(*GoSayHelloRequest)(nil),    // 0: pb.GoSayHelloRequest
	(*GoSayHelloResponse)(nil),   // 1: pb.GoSayHelloResponse
	(*NotifyActionRequest)(nil),  // 2: pb.NotifyActionRequest
	(*NotifyActionResponse)(nil), // 3: pb.NotifyActionResponse
	(*Base)(nil),                 // 4: pb.Base
	(*Action)(nil),               // 5: pb.Action
	(*State)(nil),                // 6: pb.State
	(*Feedback)(nil),             // 7: pb.Feedback
}
var file_go_proto_depIdxs = []int32{
	4, // 0: pb.NotifyActionRequest.Base:type_name -> pb.Base
	5, // 1: pb.NotifyActionRequest.Action:type_name -> pb.Action
	6, // 2: pb.NotifyActionRequest.State:type_name -> pb.State
	4, // 3: pb.NotifyActionResponse.Base:type_name -> pb.Base
	7, // 4: pb.NotifyActionResponse.Feedback:type_name -> pb.Feedback
	0, // 5: pb.ServerApi.GoSayHello:input_type -> pb.GoSayHelloRequest
	2, // 6: pb.ServerApi.NotifyAction:input_type -> pb.NotifyActionRequest
	1, // 7: pb.ServerApi.GoSayHello:output_type -> pb.GoSayHelloResponse
	3, // 8: pb.ServerApi.NotifyAction:output_type -> pb.NotifyActionResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_go_proto_init() }
func file_go_proto_init() {
	if File_go_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_go_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoSayHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoSayHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_proto_goTypes,
		DependencyIndexes: file_go_proto_depIdxs,
		MessageInfos:      file_go_proto_msgTypes,
	}.Build()
	File_go_proto = out.File
	file_go_proto_rawDesc = nil
	file_go_proto_goTypes = nil
	file_go_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServerApiClient is the client API for ServerApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerApiClient interface {
	GoSayHello(ctx context.Context, in *GoSayHelloRequest, opts ...grpc.CallOption) (*GoSayHelloResponse, error)
	NotifyAction(ctx context.Context, in *NotifyActionRequest, opts ...grpc.CallOption) (*NotifyActionResponse, error)
}

type serverApiClient struct {
	cc grpc.ClientConnInterface
}

func NewServerApiClient(cc grpc.ClientConnInterface) ServerApiClient {
	return &serverApiClient{cc}
}

func (c *serverApiClient) GoSayHello(ctx context.Context, in *GoSayHelloRequest, opts ...grpc.CallOption) (*GoSayHelloResponse, error) {
	out := new(GoSayHelloResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerApi/GoSayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverApiClient) NotifyAction(ctx context.Context, in *NotifyActionRequest, opts ...grpc.CallOption) (*NotifyActionResponse, error) {
	out := new(NotifyActionResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerApi/NotifyAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerApiServer is the server API for ServerApi service.
type ServerApiServer interface {
	GoSayHello(context.Context, *GoSayHelloRequest) (*GoSayHelloResponse, error)
	NotifyAction(context.Context, *NotifyActionRequest) (*NotifyActionResponse, error)
}

// UnimplementedServerApiServer can be embedded to have forward compatible implementations.
type UnimplementedServerApiServer struct {
}

func (*UnimplementedServerApiServer) GoSayHello(context.Context, *GoSayHelloRequest) (*GoSayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoSayHello not implemented")
}
func (*UnimplementedServerApiServer) NotifyAction(context.Context, *NotifyActionRequest) (*NotifyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyAction not implemented")
}

func RegisterServerApiServer(s *grpc.Server, srv ServerApiServer) {
	s.RegisterService(&_ServerApi_serviceDesc, srv)
}

func _ServerApi_GoSayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoSayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerApiServer).GoSayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerApi/GoSayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerApiServer).GoSayHello(ctx, req.(*GoSayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerApi_NotifyAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerApiServer).NotifyAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerApi/NotifyAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerApiServer).NotifyAction(ctx, req.(*NotifyActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServerApi",
	HandlerType: (*ServerApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoSayHello",
			Handler:    _ServerApi_GoSayHello_Handler,
		},
		{
			MethodName: "NotifyAction",
			Handler:    _ServerApi_NotifyAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.proto",
}
