// python.proto
// [python quickstart](https://grpc.io/docs/quickstart/python.html#run-a-grpc-application)

// python -m grpc_tools.protoc --python_out=../python/grpc --grpc_python_out=../python/grpc -I. python.proto
// protoc --proto_path=./pb/ --go_out=plugins=grpc:./grpc python.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: python.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_python_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_python_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_python_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_python_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TrainStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base  *Base  `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	State *State `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *TrainStepRequest) Reset() {
	*x = TrainStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_python_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainStepRequest) ProtoMessage() {}

func (x *TrainStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainStepRequest.ProtoReflect.Descriptor instead.
func (*TrainStepRequest) Descriptor() ([]byte, []int) {
	return file_python_proto_rawDescGZIP(), []int{2}
}

func (x *TrainStepRequest) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *TrainStepRequest) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

type TrainStepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *Base `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
}

func (x *TrainStepResponse) Reset() {
	*x = TrainStepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_python_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainStepResponse) ProtoMessage() {}

func (x *TrainStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainStepResponse.ProtoReflect.Descriptor instead.
func (*TrainStepResponse) Descriptor() ([]byte, []int) {
	return file_python_proto_rawDescGZIP(), []int{3}
}

func (x *TrainStepResponse) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_python_proto protoreflect.FileDescriptor

var file_python_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x23, 0x0a, 0x0f, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x10, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x51, 0x0a, 0x10, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x31,
	0x0a, 0x11, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x42, 0x61, 0x73,
	0x65, 0x32, 0x7f, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x37, 0x0a,
	0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x65, 0x70, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74,
	0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_python_proto_rawDescOnce sync.Once
	file_python_proto_rawDescData = file_python_proto_rawDesc
)

func file_python_proto_rawDescGZIP() []byte {
	file_python_proto_rawDescOnce.Do(func() {
		file_python_proto_rawDescData = protoimpl.X.CompressGZIP(file_python_proto_rawDescData)
	})
	return file_python_proto_rawDescData
}

var file_python_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_python_proto_goTypes = []interface{}{
	(*SayHelloRequest)(nil),   // 0: pb.SayHelloRequest
	(*SayHelloResponse)(nil),  // 1: pb.SayHelloResponse
	(*TrainStepRequest)(nil),  // 2: pb.TrainStepRequest
	(*TrainStepResponse)(nil), // 3: pb.TrainStepResponse
	(*Base)(nil),              // 4: pb.Base
	(*State)(nil),             // 5: pb.State
}
var file_python_proto_depIdxs = []int32{
	4, // 0: pb.TrainStepRequest.Base:type_name -> pb.Base
	5, // 1: pb.TrainStepRequest.State:type_name -> pb.State
	4, // 2: pb.TrainStepResponse.Base:type_name -> pb.Base
	0, // 3: pb.TrainApi.SayHello:input_type -> pb.SayHelloRequest
	2, // 4: pb.TrainApi.TrainStep:input_type -> pb.TrainStepRequest
	1, // 5: pb.TrainApi.SayHello:output_type -> pb.SayHelloResponse
	3, // 6: pb.TrainApi.TrainStep:output_type -> pb.TrainStepResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_python_proto_init() }
func file_python_proto_init() {
	if File_python_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_python_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_python_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_python_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_python_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainStepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_python_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_python_proto_goTypes,
		DependencyIndexes: file_python_proto_depIdxs,
		MessageInfos:      file_python_proto_msgTypes,
	}.Build()
	File_python_proto = out.File
	file_python_proto_rawDesc = nil
	file_python_proto_goTypes = nil
	file_python_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TrainApiClient is the client API for TrainApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainApiClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
	TrainStep(ctx context.Context, in *TrainStepRequest, opts ...grpc.CallOption) (*TrainStepResponse, error)
}

type trainApiClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainApiClient(cc grpc.ClientConnInterface) TrainApiClient {
	return &trainApiClient{cc}
}

func (c *trainApiClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/pb.TrainApi/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainApiClient) TrainStep(ctx context.Context, in *TrainStepRequest, opts ...grpc.CallOption) (*TrainStepResponse, error) {
	out := new(TrainStepResponse)
	err := c.cc.Invoke(ctx, "/pb.TrainApi/TrainStep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainApiServer is the server API for TrainApi service.
type TrainApiServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	TrainStep(context.Context, *TrainStepRequest) (*TrainStepResponse, error)
}

// UnimplementedTrainApiServer can be embedded to have forward compatible implementations.
type UnimplementedTrainApiServer struct {
}

func (*UnimplementedTrainApiServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedTrainApiServer) TrainStep(context.Context, *TrainStepRequest) (*TrainStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainStep not implemented")
}

func RegisterTrainApiServer(s *grpc.Server, srv TrainApiServer) {
	s.RegisterService(&_TrainApi_serviceDesc, srv)
}

func _TrainApi_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainApiServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TrainApi/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainApiServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainApi_TrainStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainApiServer).TrainStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TrainApi/TrainStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainApiServer).TrainStep(ctx, req.(*TrainStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrainApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TrainApi",
	HandlerType: (*TrainApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _TrainApi_SayHello_Handler,
		},
		{
			MethodName: "TrainStep",
			Handler:    _TrainApi_TrainStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "python.proto",
}
