# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z\007../grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x02pb\"y\n\x04\x42\x61se\x12\x0f\n\x07RetCode\x18\x01 \x01(\x03\x12\x0e\n\x06RetMsg\x18\x02 \x01(\t\x12\"\n\x05\x45xtra\x18\x03 \x03(\x0b\x32\x13.pb.Base.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf5\x02\n\x05State\x12\x16\n\x04\x42\x61se\x18\x01 \x01(\x0b\x32\x08.pb.Base\x1a\x38\n\x15InboundBandwidthUsage\x12\x1f\n\x17inbound_bandwidth_usage\x18\x01 \x03(\x01\x1a:\n\x16OutboundBandwidthUsage\x12 \n\x18outbound_bandwidth_usage\x18\x01 \x03(\x01\x1a>\n\x18\x43omputationResourceUsage\x12\"\n\x1a\x43omputation_resource_usage\x18\x01 \x03(\x01\x1a]\n\x08UserInfo\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x03\x1a/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x1a?\n\rQoEPreference\x12\x0e\n\x06\x61lpha1\x18\x01 \x01(\x05\x12\x0e\n\x06\x61lpha2\x18\x02 \x01(\x05\x12\x0e\n\x06\x61lpha3\x18\x03 \x01(\x05\"U\n\x06\x41\x63tion\x12\x16\n\x04\x42\x61se\x18\x01 \x01(\x0b\x32\x08.pb.Base\x12\x0e\n\x06Reward\x18\x02 \x01(\x01\x12\x13\n\x0bPossibility\x18\x03 \x03(\x01\x12\x0e\n\x06\x41\x63tion\x18\x04 \x01(\x03\"D\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x16\n\x04\x42\x61se\x18\x01 \x01(\x0b\x32\x08.pb.Base\x12\x0e\n\x06Reward\x18\x02 \x01(\x01\x12\x10\n\x08\x41\x63\x63uracy\x18\x03 \x01(\x01\x42\tZ\x07../grpcb\x06proto3'
)




_BASE_EXTRAENTRY = _descriptor.Descriptor(
  name='ExtraEntry',
  full_name='pb.Base.ExtraEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.Base.ExtraEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.Base.ExtraEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=141,
)

_BASE = _descriptor.Descriptor(
  name='Base',
  full_name='pb.Base',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RetCode', full_name='pb.Base.RetCode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RetMsg', full_name='pb.Base.RetMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Extra', full_name='pb.Base.Extra', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BASE_EXTRAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=141,
)


_STATE_INBOUNDBANDWIDTHUSAGE = _descriptor.Descriptor(
  name='InboundBandwidthUsage',
  full_name='pb.State.InboundBandwidthUsage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inbound_bandwidth_usage', full_name='pb.State.InboundBandwidthUsage.inbound_bandwidth_usage', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=233,
)

_STATE_OUTBOUNDBANDWIDTHUSAGE = _descriptor.Descriptor(
  name='OutboundBandwidthUsage',
  full_name='pb.State.OutboundBandwidthUsage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='outbound_bandwidth_usage', full_name='pb.State.OutboundBandwidthUsage.outbound_bandwidth_usage', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=293,
)

_STATE_COMPUTATIONRESOURCEUSAGE = _descriptor.Descriptor(
  name='ComputationResourceUsage',
  full_name='pb.State.ComputationResourceUsage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Computation_resource_usage', full_name='pb.State.ComputationResourceUsage.Computation_resource_usage', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=357,
)

_STATE_USERINFO_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='pb.State.UserInfo.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='pb.State.UserInfo.Location.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='pb.State.UserInfo.Location.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=452,
)

_STATE_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='pb.State.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='pb.State.UserInfo.channel', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='pb.State.UserInfo.version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATE_USERINFO_LOCATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=452,
)

_STATE_QOEPREFERENCE = _descriptor.Descriptor(
  name='QoEPreference',
  full_name='pb.State.QoEPreference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha1', full_name='pb.State.QoEPreference.alpha1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alpha2', full_name='pb.State.QoEPreference.alpha2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alpha3', full_name='pb.State.QoEPreference.alpha3', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=517,
)

_STATE = _descriptor.Descriptor(
  name='State',
  full_name='pb.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Base', full_name='pb.State.Base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATE_INBOUNDBANDWIDTHUSAGE, _STATE_OUTBOUNDBANDWIDTHUSAGE, _STATE_COMPUTATIONRESOURCEUSAGE, _STATE_USERINFO, _STATE_QOEPREFERENCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=517,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='pb.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Base', full_name='pb.Action.Base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Reward', full_name='pb.Action.Reward', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Possibility', full_name='pb.Action.Possibility', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Action', full_name='pb.Action.Action', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=604,
)


_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='pb.Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Base', full_name='pb.Feedback.Base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Reward', full_name='pb.Feedback.Reward', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Accuracy', full_name='pb.Feedback.Accuracy', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=674,
)

_BASE_EXTRAENTRY.containing_type = _BASE
_BASE.fields_by_name['Extra'].message_type = _BASE_EXTRAENTRY
_STATE_INBOUNDBANDWIDTHUSAGE.containing_type = _STATE
_STATE_OUTBOUNDBANDWIDTHUSAGE.containing_type = _STATE
_STATE_COMPUTATIONRESOURCEUSAGE.containing_type = _STATE
_STATE_USERINFO_LOCATION.containing_type = _STATE_USERINFO
_STATE_USERINFO.containing_type = _STATE
_STATE_QOEPREFERENCE.containing_type = _STATE
_STATE.fields_by_name['Base'].message_type = _BASE
_ACTION.fields_by_name['Base'].message_type = _BASE
_FEEDBACK.fields_by_name['Base'].message_type = _BASE
DESCRIPTOR.message_types_by_name['Base'] = _BASE
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Base = _reflection.GeneratedProtocolMessageType('Base', (_message.Message,), {

  'ExtraEntry' : _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), {
    'DESCRIPTOR' : _BASE_EXTRAENTRY,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:pb.Base.ExtraEntry)
    })
  ,
  'DESCRIPTOR' : _BASE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:pb.Base)
  })
_sym_db.RegisterMessage(Base)
_sym_db.RegisterMessage(Base.ExtraEntry)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {

  'InboundBandwidthUsage' : _reflection.GeneratedProtocolMessageType('InboundBandwidthUsage', (_message.Message,), {
    'DESCRIPTOR' : _STATE_INBOUNDBANDWIDTHUSAGE,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:pb.State.InboundBandwidthUsage)
    })
  ,

  'OutboundBandwidthUsage' : _reflection.GeneratedProtocolMessageType('OutboundBandwidthUsage', (_message.Message,), {
    'DESCRIPTOR' : _STATE_OUTBOUNDBANDWIDTHUSAGE,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:pb.State.OutboundBandwidthUsage)
    })
  ,

  'ComputationResourceUsage' : _reflection.GeneratedProtocolMessageType('ComputationResourceUsage', (_message.Message,), {
    'DESCRIPTOR' : _STATE_COMPUTATIONRESOURCEUSAGE,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:pb.State.ComputationResourceUsage)
    })
  ,

  'UserInfo' : _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {

    'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
      'DESCRIPTOR' : _STATE_USERINFO_LOCATION,
      '__module__' : 'common_pb2'
      # @@protoc_insertion_point(class_scope:pb.State.UserInfo.Location)
      })
    ,
    'DESCRIPTOR' : _STATE_USERINFO,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:pb.State.UserInfo)
    })
  ,

  'QoEPreference' : _reflection.GeneratedProtocolMessageType('QoEPreference', (_message.Message,), {
    'DESCRIPTOR' : _STATE_QOEPREFERENCE,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:pb.State.QoEPreference)
    })
  ,
  'DESCRIPTOR' : _STATE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:pb.State)
  })
_sym_db.RegisterMessage(State)
_sym_db.RegisterMessage(State.InboundBandwidthUsage)
_sym_db.RegisterMessage(State.OutboundBandwidthUsage)
_sym_db.RegisterMessage(State.ComputationResourceUsage)
_sym_db.RegisterMessage(State.UserInfo)
_sym_db.RegisterMessage(State.UserInfo.Location)
_sym_db.RegisterMessage(State.QoEPreference)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:pb.Action)
  })
_sym_db.RegisterMessage(Action)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:pb.Feedback)
  })
_sym_db.RegisterMessage(Feedback)


DESCRIPTOR._options = None
_BASE_EXTRAENTRY._options = None
# @@protoc_insertion_point(module_scope)
