# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import go_pb2 as go__pb2


class ServerApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GoSayHello = channel.unary_unary(
                '/pb.ServerApi/GoSayHello',
                request_serializer=go__pb2.GoSayHelloRequest.SerializeToString,
                response_deserializer=go__pb2.GoSayHelloResponse.FromString,
                )
        self.NotifyAction = channel.unary_unary(
                '/pb.ServerApi/NotifyAction',
                request_serializer=go__pb2.NotifyActionRequest.SerializeToString,
                response_deserializer=go__pb2.NotifyActionResponse.FromString,
                )


class ServerApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GoSayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GoSayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.GoSayHello,
                    request_deserializer=go__pb2.GoSayHelloRequest.FromString,
                    response_serializer=go__pb2.GoSayHelloResponse.SerializeToString,
            ),
            'NotifyAction': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyAction,
                    request_deserializer=go__pb2.NotifyActionRequest.FromString,
                    response_serializer=go__pb2.NotifyActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ServerApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GoSayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ServerApi/GoSayHello',
            go__pb2.GoSayHelloRequest.SerializeToString,
            go__pb2.GoSayHelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ServerApi/NotifyAction',
            go__pb2.NotifyActionRequest.SerializeToString,
            go__pb2.NotifyActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
