# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='go.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z\007../grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08go.proto\x12\x02pb\x1a\x0c\x63ommon.proto\" \n\x11GoSayHelloRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x12GoSayHelloResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"c\n\x13NotifyActionRequest\x12\x16\n\x04\x42\x61se\x18\x01 \x01(\x0b\x32\x08.pb.Base\x12\x1a\n\x06\x41\x63tion\x18\x02 \x01(\x0b\x32\n.pb.Action\x12\x18\n\x05State\x18\x03 \x01(\x0b\x32\t.pb.State\"N\n\x14NotifyActionResponse\x12\x16\n\x04\x42\x61se\x18\x01 \x01(\x0b\x32\x08.pb.Base\x12\x1e\n\x08\x46\x65\x65\x64\x62\x61\x63k\x18\x02 \x01(\x0b\x32\x0c.pb.Feedback2\x8f\x01\n\tServerApi\x12=\n\nGoSayHello\x12\x15.pb.GoSayHelloRequest\x1a\x16.pb.GoSayHelloResponse\"\x00\x12\x43\n\x0cNotifyAction\x12\x17.pb.NotifyActionRequest\x1a\x18.pb.NotifyActionResponse\"\x00\x42\tZ\x07../grpcb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_GOSAYHELLOREQUEST = _descriptor.Descriptor(
  name='GoSayHelloRequest',
  full_name='pb.GoSayHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='pb.GoSayHelloRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=62,
)


_GOSAYHELLORESPONSE = _descriptor.Descriptor(
  name='GoSayHelloResponse',
  full_name='pb.GoSayHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='pb.GoSayHelloResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=97,
)


_NOTIFYACTIONREQUEST = _descriptor.Descriptor(
  name='NotifyActionRequest',
  full_name='pb.NotifyActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Base', full_name='pb.NotifyActionRequest.Base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Action', full_name='pb.NotifyActionRequest.Action', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='State', full_name='pb.NotifyActionRequest.State', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=198,
)


_NOTIFYACTIONRESPONSE = _descriptor.Descriptor(
  name='NotifyActionResponse',
  full_name='pb.NotifyActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Base', full_name='pb.NotifyActionResponse.Base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Feedback', full_name='pb.NotifyActionResponse.Feedback', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=278,
)

_NOTIFYACTIONREQUEST.fields_by_name['Base'].message_type = common__pb2._BASE
_NOTIFYACTIONREQUEST.fields_by_name['Action'].message_type = common__pb2._ACTION
_NOTIFYACTIONREQUEST.fields_by_name['State'].message_type = common__pb2._STATE
_NOTIFYACTIONRESPONSE.fields_by_name['Base'].message_type = common__pb2._BASE
_NOTIFYACTIONRESPONSE.fields_by_name['Feedback'].message_type = common__pb2._FEEDBACK
DESCRIPTOR.message_types_by_name['GoSayHelloRequest'] = _GOSAYHELLOREQUEST
DESCRIPTOR.message_types_by_name['GoSayHelloResponse'] = _GOSAYHELLORESPONSE
DESCRIPTOR.message_types_by_name['NotifyActionRequest'] = _NOTIFYACTIONREQUEST
DESCRIPTOR.message_types_by_name['NotifyActionResponse'] = _NOTIFYACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GoSayHelloRequest = _reflection.GeneratedProtocolMessageType('GoSayHelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _GOSAYHELLOREQUEST,
  '__module__' : 'go_pb2'
  # @@protoc_insertion_point(class_scope:pb.GoSayHelloRequest)
  })
_sym_db.RegisterMessage(GoSayHelloRequest)

GoSayHelloResponse = _reflection.GeneratedProtocolMessageType('GoSayHelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _GOSAYHELLORESPONSE,
  '__module__' : 'go_pb2'
  # @@protoc_insertion_point(class_scope:pb.GoSayHelloResponse)
  })
_sym_db.RegisterMessage(GoSayHelloResponse)

NotifyActionRequest = _reflection.GeneratedProtocolMessageType('NotifyActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYACTIONREQUEST,
  '__module__' : 'go_pb2'
  # @@protoc_insertion_point(class_scope:pb.NotifyActionRequest)
  })
_sym_db.RegisterMessage(NotifyActionRequest)

NotifyActionResponse = _reflection.GeneratedProtocolMessageType('NotifyActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYACTIONRESPONSE,
  '__module__' : 'go_pb2'
  # @@protoc_insertion_point(class_scope:pb.NotifyActionResponse)
  })
_sym_db.RegisterMessage(NotifyActionResponse)


DESCRIPTOR._options = None

_SERVERAPI = _descriptor.ServiceDescriptor(
  name='ServerApi',
  full_name='pb.ServerApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=424,
  methods=[
  _descriptor.MethodDescriptor(
    name='GoSayHello',
    full_name='pb.ServerApi.GoSayHello',
    index=0,
    containing_service=None,
    input_type=_GOSAYHELLOREQUEST,
    output_type=_GOSAYHELLORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NotifyAction',
    full_name='pb.ServerApi.NotifyAction',
    index=1,
    containing_service=None,
    input_type=_NOTIFYACTIONREQUEST,
    output_type=_NOTIFYACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERAPI)

DESCRIPTOR.services_by_name['ServerApi'] = _SERVERAPI

# @@protoc_insertion_point(module_scope)
